### ISSUE TITLE
Bower can't find file

### ISSUE THREAD

**Issue by anthonycollini** [Robdel12/DropKick#293]
Having an issue where bower won't install dropkick. I'm using ember and I cleared npm and bower cache.

I am also using the ember add-on

My bower file has: `"dropkick": "~2.1.4"`

package.json has: `"ember-dropkick": "0.1.1"`

Here's the output I am getting:

    Build failed.
    Path or pattern "bower_components/dropkick/dropkick.js" did not match any files
    Error: Path or pattern "bower_components/dropkick/dropkick.js" did not match any files
        at Object.multiGlob (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/broccoli-kitchen-sink-helpers/index.js:202:13)
        at Class.module.exports.CachingWriter.extend.addFiles (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:74:13)
        at Class.module.exports.CachingWriter.extend.updateCache (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/concat-with-maps.js:52:12)
        at /Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/broccoli-sourcemap-concat/node_modules/broccoli-caching-writer/index.js:92:34
        at lib$rsvp$$internal$$tryCatch (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:489:16)
        at lib$rsvp$$internal$$invokeCallback (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:501:17)
        at lib$rsvp$$internal$$publish (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:472:11)
        at lib$rsvp$asap$$flush (/Users/ac/code/#####/web-client/node_modules/ember-cli/node_modules/rsvp/dist/rsvp.js:1290:9)
        at process._tickCallback (node.js:355:11)

Here's a pic of bower.json file from the version of dropkick installed by bower, in which the file structures don't seem to match up.

![screenshot 2015-05-20 15 37 59](https://cloud.githubusercontent.com/assets/933222/7734806/cd62dcac-ff06-11e4-83c9-a95254f9c04d.png)

**Comment by Robdel12** [comment]
If you update ember-dropkick to 0.1.2 you should be able to build again. I forgot to update the path in the brocfile. One day I'll be able to release something smoothly :P

Thank for the heads up @anthonycollini! Hope all is well with you :)
